services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: cloud_file_storage
      POSTGRES_USER: yuubi123
      POSTGRES_PASSWORD: yuubi123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: yuubi123
      MINIO_ROOT_PASSWORD: yuubi123
    volumes:
      - minio_data:/data
    command: server /data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  minio_data:
  redis_data:































