services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: cloud_file_storage
      POSTGRES_USER: yuubi
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data

volumes:
  minio_data:
    driver: local
































